source 'https://rubygems.org/'

gem 'nokogiri' # HTML parser
gem 'open-uri' # URL opener or makes request to URL
gem 'sinatra' # CSV parser or makes CSV files
gem 'json' # JSON parser or makes JSON files